version: '3'

services:
  jupyter:
    image: dockgobusan/dl:0.3
    container_name: dl
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./:/app
      - ./notebooks:/app/notebooks
    # depends_on:
    #   - mysql
    # command: sh -c "while ! nc -z mysql 3306; do sleep 1; done && jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
    networks:
      - default
    restart: always

  # mysql:
  #   container_name: database
  #   image: mysql:8.0.36
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     TZ: Asia/Seoul
  #   networks:
  #     - default
  #   volumes:
  #     - ./data/mysql/:/var/lib/mysql
  #   restart: always

networks:
  default:
